# Generated by Django 6.0.7 on 2026-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='xp_reward',
            field=models.IntegerField(default=20),
        ),
    ]
