# Generated by Django 6.0.7 on 2026-08-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
