# Generated by Django 6.0.7 on 2026-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog_xp_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health & Wellness'), ('fitness', 'Fitness & Exercise'), ('study', 'Study & Learning'), ('work', 'Work & Career'), ('personal', 'Personal Development'), ('mindfulness', 'Mindfulness & Meditation'), ('creative', 'Creative Hobbies'), ('social', 'Social & Relationships'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
