# Generated by Django 6.0.7 on 2026-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_xp_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_soon_notified_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_notified_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
