# Generated by Django 6.0.7 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[
                ('TASK_REMINDER', 'Task Reminder'),
                ('HABIT_REMINDER', 'Habit Reminder'),
                ('GOAL_DEADLINE', 'Goal Deadline'),
                ('POMODORO_ABANDONED', 'Pomodoro Abandoned'),
                ('FOCUS_COMPLETED', 'Focus Session Completed'),
                ('TASK_COMPLETED', 'Task Completed'),
                ('HABIT_COMPLETED', 'Habit Completed'),
                ('STREAK_MILESTONE', 'Streak Milestone'),
                ('STUDY_COMPLETED', 'Study Session Completed'),
                ('MILESTONE_COMPLETED', 'Milestone Completed'),
                ('GOAL_COMPLETED', 'Goal Completed'),
                ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked'),
            ], max_length=25),
        ),
    ]
