# Generated by Django 6.0.7 on 2026-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='toast_pending',
            field=models.BooleanField(default=False),
        ),
    ]
